<?php

/**
 * @file
 * Contains svgtoolkit.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_form_alter().
 *
 * Add svg to the list of permitted file extensions on image widgets.
 *
 * @param $element
 * @param FormStateInterface $form_state
 * @param $context
 */
function svgtoolkit_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  /** @var \Drupal\Core\Field\WidgetInterface $widget */
  $widget = $context['widget'];
  $definition = $widget->getPluginDefinition();
  if (in_array('image', $definition['field_types'])) {
    $extensions = $element['#upload_validators']['file_validate_extensions'][0];
    $element['#upload_validators']['file_validate_extensions'][0] = $extensions .' svg';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add svg to the list of permitted file extensions on image uploads in editor.
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function svgtoolkit_form_editor_image_dialog_alter(&$form, FormStateInterface $form_state) {
  $extensions = $form['fid']['#upload_validators']['file_validate_extensions'][0];
  $form['fid']['#upload_validators']['file_validate_extensions'][0] = $extensions .' svg';
}
